---
 - name: Install Apache and upload page
   hosts: all
   become: yes

   vars:
     source_file: ./website/index.html
     destin_file: /var/www/html


   tasks:
   - name: Install Apache Web Server
     yum: name=httpd state=latest

   - name: Copy page to Servers
     copy: src={{ source_file }} dest={{ destin_file }} mode=0555
     notify: Restart Apache

   - name: Start Web Server and enable on boot
     service: name=httpd state=started enabled=yes  


   handlers:
   - name: Restart Apache
     service: name=httpd state=restarted   