---
 - name: My Test
   hosts: all
   become: yes

   vars:
    message1: Privet
    message2: World
    secret  : DFDFDFDFDFDF


   tasks:

    - name: Print Secret variable
      debug:
        var: secret

    - debug:
        msg: "Secret word : {{ secret }}"

    - debug:
        msg: "Admin this server ---> Kirill"   

    - set_fact: full_message="{{ message1 }} {{ message2 }} from Kirill"

    - debug: 
        var: full_message

    - debug:
        var: ansible_distribution

    - shell: uptime
      register: result
    
    - debug:
        var: result      